[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1
sleepApplication = false

[[deploy.volumes]]
name = "tor-keys"
mountPath = "/var/lib/tor"

[[deploy.variables]]
name = "NODE_ENV"
value = "production"

[[deploy.variables]]
name = "PORT"
value = "8080"