-- Add more categories to expand the available options
INSERT INTO public.categories (name, description, color) VALUES
    ('Science', 'Scientific articles, research, and discoveries', '#06B6D4'),
    ('Health', 'Health, fitness, and wellness resources', '#10B981'),
    ('Finance', 'Financial news, investing, and money management', '#059669'),
    ('Business', 'Business news, entrepreneurship, and startups', '#DC2626'),
    ('Sports', 'Sports news, analysis, and updates', '#EA580C'),
    ('Travel', 'Travel guides, tips, and destination information', '#7C3AED'),
    ('Food', 'Recipes, cooking tips, and food culture', '#DB2777'),
    ('Photography', 'Photography tutorials, inspiration, and gear', '#0891B2'),
    ('Music', 'Music news, reviews, and industry updates', '#BE185D'),
    ('Books', 'Book reviews, recommendations, and literary content', '#7C2D12'),
    ('Movies', 'Film reviews, news, and entertainment industry', '#B91C1C'),
    ('Gaming', 'Video games, reviews, and gaming industry news', '#9333EA'),
    ('Art', 'Art galleries, tutorials, and creative inspiration', '#C2410C'),
    ('History', 'Historical articles, documentaries, and research', '#92400E'),
    ('Politics', 'Political news, analysis, and commentary', '#1E40AF'),
    ('Environment', 'Environmental news, climate change, and sustainability', '#16A34A'),
    ('Cryptocurrency', 'Crypto news, blockchain, and digital assets', '#F59E0B'),
    ('AI & Machine Learning', 'Artificial intelligence and ML resources', '#6366F1'),
    ('Cybersecurity', 'Security news, tutorials, and best practices', '#DC2626'),
    ('Mobile Development', 'Mobile app development and tutorials', '#059669'),
    ('Web Development', 'Web development tutorials and resources', '#0EA5E9'),
    ('DevOps', 'DevOps tools, practices, and automation', '#7C3AED'),
    ('Data Science', 'Data analysis, visualization, and statistics', '#DB2777'),
    ('Productivity', 'Productivity tools, tips, and life hacks', '#0891B2'),
    ('Career', 'Career advice, job hunting, and professional development', '#BE185D'),
    ('Startups', 'Startup news, funding, and entrepreneurship', '#7C2D12'),
    ('Marketing', 'Digital marketing, SEO, and growth strategies', '#B91C1C'),
    ('Social Media', 'Social media trends, tools, and strategies', '#9333EA'),
    ('Podcasts', 'Podcast recommendations and audio content', '#C2410C'),
    ('YouTube', 'YouTube channels, tutorials, and video content', '#DC2626'),
    ('Open Source', 'Open source projects, contributions, and community', '#16A34A'),
    ('Hardware', 'Computer hardware, reviews, and tech specs', '#F59E0B'),
    ('Software', 'Software reviews, tools, and applications', '#6366F1'),
    ('Tutorials', 'Step-by-step guides and how-to content', '#059669'),
    ('Documentation', 'Technical documentation and reference materials', '#0EA5E9'),
    ('APIs', 'API documentation, tools, and integrations', '#7C3AED'),
    ('Databases', 'Database tutorials, optimization, and management', '#DB2777'),
    ('Cloud Computing', 'Cloud services, AWS, Azure, and GCP resources', '#0891B2'),
    ('Networking', 'Network administration, protocols, and security', '#BE185D'),
    ('Linux', 'Linux tutorials, distributions, and system administration', '#7C2D12'),
    ('Forums', 'Discussion forums, communities, and message boards', '#6B7280'),
    ('Dark Net Markets', 'Dark web marketplaces and onion services', '#374151')
ON CONFLICT (name) DO NOTHING;